package tgo1014.webgados.model.objects

import android.arch.persistence.room.Entity
import android.arch.persistence.room.PrimaryKey

@Entity
data class Ad(
        @PrimaryKey val _id: String = "",
        val adType: String = "",
        val age_max: String = "",
        val age_min: String = "",
        val approved_at: String = "",
        val auditAt: String = "",
        val auditRef: String = "",
        val average_weight: String = "",
        val category_name: String = "",
        val classificacao: String = "",
        val created_at: String = "",
        val created_at_unix: String = "",
        val description: String = "",
        val expiration_date: String = "",
        val expire_at: String = "",
        val farm: Farm = Farm(),
        val fase: String = "",
        val favorite: String = "",
        val featured: String = "",
        val gender: String = "",
        val habilidades: Array<String> = arrayOf(),
        val head_count: String = "",
        val id: String = "",
        val kind_name: String = "",
        val list_partner_ad: String = "",
        val location: Array<String> = arrayOf(),
        val meio_sangue: String = "",
        val modified_at: String = "",
        val photos_url: Array<String> = arrayOf(),
        val price: String = "",
        val price_type: String = "",
        val racas: Array<String> = arrayOf(),
        val renewals: Array<String> = arrayOf(),
        val seller_celular: String = "",
        val seller_id: String = "",
        val seller_name: String = "",
        val seller_rating: String = "",
        var seller_avatar: String = "",
        val sku: String = "",
        val slug: String = "",
        val status: String = "",
        val subcategory_name: String = "",
        val title: String = "",
        val title_search: String = "",
        val treinamentos: Array<String> = arrayOf(),
        val unit_value: String = "",
        val updates: Array<String> = arrayOf(),
        val video_url: String = "",
        val views_count: String = "",
        val weight_type: String = "",
        val years: String = "",
        var months: String = "")